state_names = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas", "CA": "California",
    "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware", "FL": "Florida", "GA": "Georgia",
    "HI": "Hawaii", "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas",
    "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland", "MA": "Massachusetts",
    "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi", "MO": "Missouri", "MT": "Montana",
    "NE": "Nebraska", "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico",
    "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma",
    "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina",
    "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah", "VT": "Vermont",
    "VA": "Virginia", "WA": "Washington", "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming"
}

state_cities = {
    "AL": ["BHM", "HSV"],
    "AK": ["ANC", "FAI"],
    "AZ": ["PHX", "TUS"],
    "AR": ["LIT", "XNA"],
    "CA": ["LAX", "SFO", "SAN"],
    "CO": ["DEN"],
    "CT": ["BDL"],
    "DE": ["ILG"],
    "FL": ["MIA", "TPA", "MCO"],
    "GA": ["ATL", "SAV"],
    "HI": ["HNL"],
    "ID": ["BOI"],
    "IL": ["ORD", "MDW"],
    "IN": ["IND"],
    "IA": ["DSM"],
    "KS": ["ICT"],
    "KY": ["CVG", "SDF"],
    "LA": ["MSY"],
    "ME": ["PWM"],
    "MD": ["BWI"],
    "MA": ["BOS"],
    "MI": ["DTW"],
    "MN": ["MSP"],
    "MS": ["JAN"],
    "MO": ["STL", "MCI"],
    "MT": ["BZN"],
    "NE": ["OMA"],
    "NV": ["LAS"],
    "NH": ["MHT"],
    "NJ": ["EWR"],
    "NM": ["ABQ"],
    "NY": ["JFK", "LGA", "BUF"],
    "NC": ["CLT", "RDU"],
    "ND": ["FAR"],
    "OH": ["CLE", "CMH"],
    "OK": ["OKC"],
    "OR": ["PDX"],
    "PA": ["PHL", "PIT"],
    "RI": ["PVD"],
    "SC": ["CHS"],
    "SD": ["FSD"],
    "TN": ["BNA", "MEM"],
    "TX": ["DFW", "IAH", "AUS"],
    "UT": ["SLC"],
    "VT": ["BTV"],
    "VA": ["DCA", "RIC"],
    "WA": ["SEA"],
    "WV": ["CRW"],
    "WI": ["MKE"],
    "WY": ["JAC"]
}

city_names = {
    "BHM": "Birmingham", "HSV": "Huntsville", "ANC": "Anchorage", "FAI": "Fairbanks",
    "PHX": "Phoenix", "TUS": "Tucson", "LIT": "Little Rock", "XNA": "Fayetteville",
    "LAX": "Los Angeles", "SFO": "San Francisco", "SAN": "San Diego", "DEN": "Denver",
    "BDL": "Hartford", "ILG": "Wilmington", "MIA": "Miami", "TPA": "Tampa", "MCO": "Orlando",
    "ATL": "Atlanta", "SAV": "Savannah", "HNL": "Honolulu", "BOI": "Boise", "ORD": "Chicago",
    "MDW": "Chicago", "IND": "Indianapolis", "DSM": "Des Moines", "ICT": "Wichita",
    "CVG": "Cincinnati", "SDF": "Louisville", "MSY": "New Orleans", "PWM": "Portland",
    "BWI": "Baltimore", "BOS": "Boston", "DTW": "Detroit", "MSP": "Minneapolis",
    "JAN": "Jackson", "STL": "St. Louis", "MCI": "Kansas City", "BZN": "Bozeman",
    "OMA": "Omaha", "LAS": "Las Vegas", "MHT": "Manchester", "EWR": "Newark",
    "ABQ": "Albuquerque", "JFK": "New York", "LGA": "New York", "BUF": "Buffalo",
    "CLT": "Charlotte", "RDU": "Raleigh", "FAR": "Fargo", "CLE": "Cleveland",
    "CMH": "Columbus", "OKC": "Oklahoma City", "PDX": "Portland", "PHL": "Philadelphia",
    "PIT": "Pittsburgh", "PVD": "Providence", "CHS": "Charleston", "FSD": "Sioux Falls",
    "BNA": "Nashville", "MEM": "Memphis", "DFW": "Dallas", "IAH": "Houston", "AUS": "Austin",
    "SLC": "Salt Lake City", "BTV": "Burlington", "DCA": "Washington", "RIC": "Richmond",
    "SEA": "Seattle", "CRW": "Charleston", "MKE": "Milwaukee", "JAC": "Jackson Hole"
}